version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    container_name: minio
    restart: unless-stopped
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "tree"
      MINIO_ROOT_PASSWORD: "ZX60gI7IdAc9eiI1"
      MINIO_REGION_NAME: "cn-outline-1"
      MINIO_BROWSER: "on"
      MINIO_SERVER_URL: "https://obs.treeyh.com/"
      MINIO_BROWSER_REDIRECT_URL: "https://obs-admin.treeyh.com/"
    volumes:
      - ${PWD}/data:/data
    command: server /data --console-address ":9001"
    networks:
      - inner_network
networks:
  inner_network:
    external: true