version: "3"
services:
  redis:
    image: ${DOCKER_REDIS_IMAGE_NAME}
    container_name: ${DOCKER_REDIS_HOSTNAME}
    restart: always
    ports:
      - 6379:6379
    command: redis-server /etc/redis.conf
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/conf/redis.conf:/etc/redis.conf
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"