version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/ssl/:/data/ssl/:ro
      - ${PWD}/logs:/data/logs:rw
      - ${PWD}/traefik/:/etc/traefik/:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:80/ping || exit 1"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1m"