version: '3.9' 

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql8
    ports:
      - "3306:3306" 
    networks:
      - inner_network
    volumes:
      - ${PWD}/data:/var/lib/mysql 
      - ${PWD}/conf:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - MYSQL_ROOT_PASSWORD=2Dv_v2VxnZ8PgG26f
    command:
      --lower_case_table_names=1

networks:
  inner_network:
    external: true