version: "3"

services:

  cronicle:
    image: soulteary/cronicle:0.9.17
    restart: always
    hostname: cronicle
    ports:
      - 3012:3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PWD}/data:/opt/cronicle/data
      - ${PWD}/logs:/opt/cronicle/logs
      - ${PWD}/plugins:/opt/cronicle/plugins
    extra_hosts:
      - "job.treeyh.com:0.0.0.0"
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"