version: "3.9"

services:
  server:
    image: gitea/gitea:1.17
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME="悦锴"
      - DOMAIN=https://git.yuekai.top:26631
      - SSH_DOMAIN=gite.yuekai.top
      - ROOT_URL=http://git.yuekai.top:26631
      - SSH_PORT=26632
      - HTTP_PORT=26631
      - DB_TYPE=mysql
      - DB_HOST=192.168.0.134:3306
      - DB_NAME=gitea_db
      - DB_USER=root
      - DB_PASSWD=7Dv_v2VxnZ8PgG26f
    restart: always
    networks:
      - inner_network
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "26631:26631"
      - "26632:26632"


networks:
  inner_network:
    external: true