version: '3.9'

services:
  xilu_hugo:
    image: klakegg/hugo:0.107.0-ext-alpine
    container_name: xilu_hugo
    user: root
    restart: always
      #command: "server --baseUrl='https://www.tree.plus' --appendPort=false --bind='0.0.0.0' "
      # command: "server --disableFastRender --bind='0.0.0.0' "
      # command: "server --disableFastRender --bind='0.0.0.0' "
    entrypoint: "/src/start_site.sh"
    ports:
      - "9094:1313"
    networks:
      - inner_network
    volumes:
      - ${PWD}/www.xilu.plus:/src
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8


networks:
  inner_network:
    external: true