version: "3.8"

services:
  # keycloak
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak16
    expose:
      - 8009
      - 8080
      - 8443
    ports:
      - 9109:8009
      - 9180:8080
      - 9143:8443
    # volumes:
    #     - /etc/timezone:/etc/timezone
    #     - /etc/localtime:/etc/localtime
    environment:
      #时区
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      # 初始化密码
      - KEYCLOAK_USER=tree
      - KEYCLOAK_PASSWORD=uhKqa1qrMvr3oIjM
      # DB
      - DB_VENDOR=postgres
      - DB_ADDR=postgres14
      - DB_PORT=5432
      - DB_DATABASE=keycloak_db
      - DB_USER=keycloak
      - DB_PASSWORD=bdpq9WfLPt47x8N0
      # 开启反向代理
      - PROXY_ADDRESS_FORWARDING=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inner_network"
      - "traefik.http.routers.halobug-sso.entrypoints=https"
      - "traefik.http.routers.halobug-sso.tls=true"
      - "traefik.http.routers.halobug-sso.rule=Host(`sso.treeyh.com`)"
      - "traefik.http.services.halobug-sso.loadbalancer.server.scheme=http"
      - "traefik.http.services.halobug-sso.loadbalancer.server.port=8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
        - inner_network
networks:
  inner_network:
    external: true